config/routes.rb
Rails.application.routes.draw do
  
  get 'goal/index'

  root 'site#index'

  get '/help', to: 'site#help', as: 'help'
  get '/about', to: 'site#about', as: 'about'
  get'/contact', to:'site#contact', as:'contact'

  #get '/search', to: 'search#index'
  #get '/report', to: 'search#report'

  # devise_for :users
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users do
    resources :logs do
    	resources :entries
    	# , only: [:show, :edit]
    end
  end

  resources :users, only: [:new, :create]

  resources :entries do 
  	resources :reports
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :log
	default_scope { order('date ASC') }
	has_many :reports


	validates :date, presence: true

	validates :food, presence: true,
	length: {minimum: 3}

	validates :mood, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10}

	# paperclip
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	# Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
 
  def index
    # to reference, entries are tied to log id, so reference log_id as in rake routes
    # so you can find log in your entries index view
    @log=Log.find(params[:log_id])

    respond_to do |format|
      format.html
      format.json { render json: @log.entries }
    end
  end
	
	def show
    if params[:q]
      #TODO REFACTOR TO ENTRY MODEL
      search = params[:q]
      if search
        resp = Typhoeus.get(
          "http://api.nal.usda.gov/usda/ndb/search",
          params: {
          format: "json",
          q: search,
          sort: "n",
          max: 30,
          offset: 0,
          api_key: "bT0Q1R0Js9aaOsjTR9ro6Oax1y21Wg2J8fmr74Vc"
          }
        )
        @foods = JSON.parse(resp.body)["list"]["item"]
      else 
        @foods = []
      end
    end
    @user = current_user
    # find the article we are interested in
    # pass in params[:id] to get :id parameter from request
    # @ is an instance variable to hold a reference to the entry object
    @entry = Entry.find(params[:id])
	end

	def new
    @entry=Entry.new
    @log=Log.find(params[:log_id])
	end

	def edit
    @entry=Entry.find(params[:id])
    @log=Log.find(params[:log_id])
	end

  def create
    @log=Log.find(params[:log_id])
    # @food_details = Entry.get_food_details(params[:ndbno_id])
    @entry = @log.entries.new(entry_params)

  # def self.get_details(ndbno_id)
  #   resp = Typhoeus.get(
  #       "http://api.nal.usda.gov/usda/ndb/reports",
  #       params: {
  #         format: "json",
  #         ndbno: nbdno_id,
  #         type: "b",
  #         api_key: "bT0Q1R0Js9aaOsjTR9ro6Oax1y21Wg2J8fmr74Vc"
  #       }
  #     )
  #   @food = JSON.parse(resp.body)["report"]
  #   return @food
  # end

# saving the model in the database
    if @entry.save
      redirect_to user_log_entry_path(current_user, @entry.log, @entry)
    else
      render 'new'
    end
  end

  def update
    @entry = Entry.find(params[:id])

    if params[:ndbno].present?
      resp = Typhoeus.get(
        "http://api.nal.usda.gov/usda/ndb/reports",
        params: {
        format: "json",
        ndbno: params[:ndbno],
        type: "b",
        api_key: "bT0Q1R0Js9aaOsjTR9ro6Oax1y21Wg2J8fmr74Vc"
        }
      )
      @food = JSON.parse(resp.body)["report"]

      @report = @entry.reports.new

      @report.name = @food["food"]["name"]
      @report.ndbno = params[:ndbno]
      @report.kcal = @food["food"]["nutrients"][1]["measures"][0]["value"]
      @report.protein = @food["food"]["nutrients"][2]["measures"][0]["value"]
      @report.fat = @food["food"]["nutrients"][3]["measures"][0]["value"]
      @report.carb = @food["food"]["nutrients"][4]["measures"][0]["value"]

      @report.save
      
      redirect_to @entry  
    end

    unless params[:ndbno].present?
      if @entry.update(entry_params)
        # redirect back to the show page with the way our routes are nested
        # @entry.log can also be params[:log_id]
        redirect_to user_log_entry_path(current_user, @entry.log, @entry)
      else
        render 'edit'
      end
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

      redirect_to user_log_path(current_user, @entry.log)
  end

# made private to make sure it can't be called outside its intended context
	private
		def entry_params
			params.require(:entry).permit(:date, :food, :mood, :avatar)
		end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<!-- tells form_for helper this is a form for :entry -->

<%= form_for [current_user, @log, @entry] do |f| %>
 
  <% if @entry.errors.any? %>
    <div id="error_explanation">

      <!-- 
        pluralize is a rails helper that takes a number and a string as its arguments. If the number is greater than one, the string will be automatically pluralized -->
      <h2>
        <%= pluralize(@entry.errors.count, "error") %> prohibited
        this entry from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <!--  f represents FormBuilder object
 used to build 1 label and 1 text field -->
  <p>
    <%= f.date_field :date %>
    <br>
    <%= f.label :date %>
    
  </p>

  <p>
    <%= f.text_field :food %>
    <br>
    <%= f.label :entry %>
  </p>

   <p>
    <%= f.number_field :mood %>
    <br>
    <%= f.label :mood %>
  </p>
    <!-- call to submit on f object will create a submit button for the form -->
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/entries/edit.html.erb
<div class ="container">
		<div class = "navbar navbar-default navbar-fixed-top">
			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">	
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<div class = "collapse navbar-collapse navHeaderCollapse">
				<ul class = "nav navbar-nav navbar-left">
	<%if (current_user)  %>
				<li class = "Log"> <%= link_to 'View a Log', user_logs_path(current_user) %> </li>
				<li class = "SignOut"><%= link_to 'Sign out', destroy_user_session_path %> </li>
	<%else  %>
				<li class= "Log In"><%= link_to 'Log In', new_user_session_path %></li>
                <li class="SignUp"><%= link_to 'Sign up', new_user_registration_path  %></li>
	<% end  %>
					<li class="About"><a href="/about">About</a></li>
					<li class="Index"><%=link_to"Home", root_path  %></li>
					<li class= "contact"><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<body class="entry">
	<div class= "container">
		<div class="jumbotron_entry">
<h1>Editing entry</h1>
 
 <%= render 'form' %>
 <br>
 <div id="back">
<button type="button" class="btn btn-default"><%= link_to 'Entries Index', user_log_entries_path(current_user, @entry.log) %></button>
</div>
<br>
 </div>
 </div>


</body>

app/views/entries/index.html.erb
<div class ="container">
		<div class = "navbar navbar-default navbar-fixed-top">
			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<div class = "collapse navbar-collapse navHeaderCollapse">
				<ul class = "nav navbar-nav navbar-left">
	<%if (current_user)  %>
				<li class = "Log"> <%= link_to 'View a Log', user_logs_path(current_user) %> </li>
				<li class = "SignOut"><%= link_to 'Sign out', destroy_user_session_path %> </li>
	<%else  %>
				<li class= "Log In"><%= link_to 'Log In', new_user_session_path %></li>
                <li class="SignUp"><%= link_to 'Sign up', new_user_registration_path  %></li>
	<% end  %>
					<li class="About"><a href="/about">About</a></li>
					<li class="Index"><%=link_to"Home", root_path  %></li>
					<li class= "contact"><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<body class="entry">
	<div class="container">
		<div class="jumbotron_entry">
<h1>Entries for Log <%=@log.id%></h1>

<!-- to view for new entry for the log that belongs to user -->
<div id="new">
<%= link_to "New Entry", new_user_log_entry_path(current_user, @log) %>
</div>	
<br>
<h3>Date:</h3>
<br>
	<% @log.entries.each do |entry| %>
	<p><%= entry.date %>
		<button><%= link_to 'Show', user_log_entry_path(current_user, @log, entry) %></button>
       	<button><%= link_to 'Edit', edit_user_log_entry_path(current_user, @log, entry) %></button>
		<button><%= link_to 'Destroy', user_log_entry_path(current_user, @log, entry),
        	method: :delete,
      		data: {confirm: 'Are you sure?'} %>

      	</button>
	</p>
	<br>
	<%end  %>
</div>
</div>
</body>

app/views/entries/new.html.erb
<div class ="container">
		<div class = "navbar navbar-default navbar-fixed-top">
			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">	
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<div class = "collapse navbar-collapse navHeaderCollapse">
				<ul class = "nav navbar-nav navbar-left">
	<%if (current_user)  %>
				<li class = "Log"> <%= link_to 'View a Log', user_logs_path(current_user) %> </li>
				<li class = "SignOut"><%= link_to 'Sign out', destroy_user_session_path %> </li>
	<%else  %>
				<li class= "Log In"><%= link_to 'Log In', new_user_session_path %></li>
                <li class="SignUp"><%= link_to 'Sign up', new_user_registration_path  %></li>
	<% end  %>
					<li class="About"><a href="/about">About</a></li>
					<li class="Index"><%=link_to"Home", root_path  %></li>
					<li class= "contact"><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<body class="entry">
		
	
	<div class="container">
		<div class="jumbotron_entry">
<h1>New Entry</h1>
<br>
<%= render 'form' %>

<br>
</div>
</div>
</body>

app/views/entries/show.html.erb
<div class ="container">
		<div class = "navbar navbar-default navbar-fixed-top">
			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">	
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<div class = "collapse navbar-collapse navHeaderCollapse">
				<ul class = "nav navbar-nav navbar-left">
	<%if (current_user)  %>
				<li class = "Log"> <%= link_to 'View a Log', user_logs_path(current_user) %> </li>
				<li class = "SignOut"><%= link_to 'Sign out', destroy_user_session_path %> </li>
	<%else  %>
				<li class= "Log In"><%= link_to 'Log In', new_user_session_path %></li>
                <li class="SignUp"><%= link_to 'Sign up', new_user_registration_path  %></li>
	<% end  %>
					<li class="About"><a href="/about">About</a></li>
					<li class="Index"><%=link_to"Home", root_path  %></li>
					<li class= "contact"><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<body class="entry">
	<div class="container">
		<div class="jumbotron_entry">
<p>
	<strong>Date:</strong>
	<%= @entry.date %>
</p>

<p>
	<strong>Entry:</strong>
	<%= @entry.food %>
</p>

<p>
	<strong>Mood:</strong>
	<%= @entry.mood %>
</p>

<p>
	<strong>Image:</strong>
	<%= image_tag @entry.avatar.url(:thumb) %>
</p>



<p>
	<strong>Food:</strong>
	<% @entry.reports.each do |report| %>
		<p>Name <%= report.name %></p>
		<p>Calories <%= report.kcal %> kcal</p>
		<p>Protein <%= report.protein %> g</p>
		<p>Carbs <%= report.carb %> g</p>
		<p>Fat <%= report.fat %> g</p>
	<% end %>
</p>

<p>
    <%= form_for entry_path, :method => 'get' do %>
      <%= label_tag(:q, "Search for food:") %> <br>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>
</p>

<p>
	<% if @foods.present? %>
	<table>
		<% @foods.each do |f| %>
			<tr>
				<td>
					<%= f["name"] %>
				</td>
				<td>
					<%= form_for entry_path, :method => 'PUT' do %>
					  <%= hidden_field(nil, :ndbno, value: f["ndbno"]) %>
					  <%= submit_tag("Add to Entry") %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
	<% end %>
</p>


<%= link_to "Back", user_log_path(current_user, @entry.log) %>
</div>
</div>
</body>