config/routes.rb
Rails.application.routes.draw do
  
  get 'goal/index'

  root 'site#index'

  get '/help', to: 'site#help', as: 'help'
  get '/about', to: 'site#about', as: 'about'
  get'/contact', to:'site#contact', as:'contact'

  #get '/search', to: 'search#index'
  #get '/report', to: 'search#report'

  # devise_for :users
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users do
    resources :logs do
    	resources :entries
    	# , only: [:show, :edit]
    end
  end

  resources :users, only: [:new, :create]

  resources :entries do 
  	resources :reports
  end

end

app/models/log.rb
class Log < ActiveRecord::Base
	has_many :entries
	default_scope { order('created_at ASC') }
	belongs_to :user
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController


	def index
		@log=Log.new
	end

	def show
		# i want to show logs/3; its a url parameter; rake routes shows :id
		@log=Log.find(params[:id])
		@entry=Entry.all
	end

	def new
	end

	def edit
		@log=Log.find(params[:id])
	end

	def create
		# calling :kind through log_params
		@log = current_user.logs.new(log_params)
		# saving the log in the database
	    if @log.save
	      redirect_to user_log_path(current_user, @log)
	    else
	      render 'new'
	    end
	end

	def update
	end

    def destroy
    	@log=Log.find(params[:id])
    	@log.destroy
    		redirect_to user_logs_path(current_user)
    	end


	# cannot call log_params in a route, unless im in the log controller; to keep it dry
	private
		def log_params
			params.require(:log).permit(:kind)
		end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<div class ="container">
		<div class = "navbar navbar-default navbar-fixed-top">
			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">	
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<div class = "collapse navbar-collapse navHeaderCollapse">
				<ul class = "nav navbar-nav navbar-left">
	<%if (current_user)  %>
				<li class = "Log"> <%= link_to 'View a Log', user_logs_path(current_user) %> </li>
				<li class = "SignOut"><%= link_to 'Sign out', destroy_user_session_path %> </li>
	<%else  %>
				<li class= "Log In"><%= link_to 'Log In', new_user_session_path %></li>
                <li class="SignUp"><%= link_to 'Sign up', new_user_registration_path  %></li>
	<% end  %>
					<li class="About"><a href="/about">About</a></li>
					<li class="Index"><%=link_to"Home", root_path  %></li>
					<li class= "contact"><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>

app/views/logs/edit.html.erb
<%=render 'form' %>
<div class="Logs">
<div class ="container">
	<div class="jumbotron_log">
<h1>Editing entry</h1>
 
 <%= render 'form' %>
 </div>
 </div>
 
<%= link_to "Back to Logs Index", user_log_path(current_user, @log) %>
</div>

app/views/logs/index.html.erb
<%=render 'form'  %>
<div class="Logs">
	<div class="container">
	<div class="jumbotron_logIndex">
<div class="new_log">
<%= form_for [current_user, @log] do |f| %>
<%= f.hidden_field :kind, value: "nutrition" %>
<%= f.submit 'New Nutrition Log' %>
<% end %>
</div>

<h2>Logs</h2>
<% current_user.logs.each do |log| %> 
	<p> 
		<h3 id="nutrition"><%=link_to 'Nutrition', user_log_path(current_user, log)%></h3>
		<button type="button" class="btn btn-default"><%= link_to 'Delete', user_log_path(current_user, log),
        	method: :delete,
      		data: {confirm: 'Are you sure?'} %> </button>
      		</p>
      		<br>
<%end%> 
</div>
</div>
</div>

app/views/logs/show.html.erb
<%=render 'form'  %>
<div class="Logs">
<div class="container">
	<div class="jumbotron_log">
<button type="button" class="btn btn-default"><%= link_to 'Back', user_logs_path(current_user) %></button>
<h1>Nutrition Log Entries</h1>
<!-- to view for new entry for the log that belongs to user -->
<button type="button" class="btn btn-default"><%= link_to "New Entry", new_user_log_entry_path(current_user, @log) %></button>
<div class=row>
	<h3>Date:</h3>
	<% @log.entries.each do |entry| %>
	<h4><%= entry.date %><h4>
		<p>
		<button type="button" class="btn btn-default"><%= link_to 'Show', user_log_entry_path(current_user, @log, entry) %></button>
       	<button type="button" class="btn btn-default"><%= link_to 'Edit', edit_user_log_entry_path(current_user, @log, entry) %></button>
		<button type="button" class="btn btn-default"><%= link_to 'Destroy', user_log_entry_path(current_user, @log, entry),
        	method: :delete,
      		data: {confirm: 'Are you sure?'} %>
      	</button>
	</p>
	
		
	<% end -%>
</div>
</div>
</div>

</div>